version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "instalando"
  pre_build:
    commands:
      - echo "fase de pre build"
  build:
    commands:
      - echo "estamos construyendo un block"
      - echo "ejecutando un test"
      - grep -Fq "nubox" index.html
  post_build:
    commands:
      - echo "estamos en la fase post build"
