---
AWSTemplateFormatVersion: '2010-09-09'
Description: This stack deploys the core infrastructure and IAM resources
             to be used for Nubox.

Parameters:
  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Default: nubox

Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://nubox-cf-file-nestedstack.s3-us-west-2.amazonaws.com/vpc.yaml'
      # Parameters:
      #   Stage: !Ref Stage
  webserver:
    Type: AWS::CloudFormation::Stack
    DependsOn: vpc
    Properties:
      TemplateURL: 'https://nubox-cf-file-nestedstack.s3-us-west-2.amazonaws.com/webserver.yaml'
      Parameters:
        KeyName: !Ref KeyName

  pipeline:
    Type: AWS::CloudFormation::Stack
    DependsOn: webserver
    Properties:
      TemplateURL: 'https://nubox-cf-file-nestedstack.s3-us-west-2.amazonaws.com/pipeline.yaml'
      # Parameters:
      #   Stage: !Ref Stage